FROM node:8-alpine

ENV PROJ_DIR=/var/local/reportek/

RUN mkdir -p $PROJ_DIR

# Only add yarn sources for caching
COPY yarn.lock package*.json $PROJ_DIR
WORKDIR $PROJ_DIR

# Yarn the madness
RUN yarn

# Copy the beloved frontend
COPY frontend/ $PROJ_DIR/frontend/

# Start the madness
CMD ["npm", "run", "dev"]
