version: '2'
services:
  db:
    image: postgres:10.1
    container_name: pg01
    expose:
      - 5432
    volumes:
      - pg_data:/var/lib/postgresql/data
      - pg_backups:/pg_backups
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    container_name: dj01
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/opt/reportek
    ports:
      - "8000:8000"
    depends_on:
      - db
  nginx:
    image: nginx:latest
    container_name: ng01
    ports:
      - "8000:8000"
    volumes:
      - .:/opt/reportek
      - .config/nginx:/etc/nginx/conf.d
    depends_on:
      - web
volumes:
  pg_data: {}
  pg_backups: {}
