version: '2'

services:
  postgres:
    image: postgres:9.6
    volumes:
      - pg_data:/var/lib/postgresql/data
      - pg_backups:/pg_backups

  app:
    image: eaudeweb/reportek2
    environment:
      - DOCKER_CONTAINER=1
      - TZ=Europe/Copenhagen
    depends_on:
      - postgres
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes

  nginx:
    image: nginx:latest
    environment:
      NGINX_CONF: |-
        upstream app {
          ip_hash;
          server app:80;
        }
        server {
          listen 80;
          access_log /var/log/nginx/access.log main;
          location / {
            proxy_pass http://app/;
          }
        }
    command: /bin/sh -c 'echo "$$NGINX_CONF" > /etc/nginx/conf.d/default.conf && exec nginx -g "daemon off;"'
    ports:
      - "8000:80"
    depends_on:
      - app

volumes:
  pg_data:
    driver: rancher-nfs
  pg_backups:
    driver: rancher-nfs
