# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-02 12:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_user_reporter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reporter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.Reporter'),
        ),
    ]
