# Generated by Django 2.0.4 on 2018-04-13 08:56

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import guardian.mixins
import reportek.core.models.reporting


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportekUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'permissions': (('act_as_reportnet_api', 'This is the user of another Reportnet service'),),
            },
            bases=(guardian.mixins.GuardianUserMixin, models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BaseWorkflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('core.demoautoqaworkflow', 'Workflow - Auto QA'), ('core.demofailqaworkflow', 'demo fail qa workflow'), ('core.demopassqaworkflow', 'demo pass qa workflow')], db_index=True, max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('previous_state', models.CharField(blank=True, max_length=60, null=True)),
                ('current_state', models.CharField(blank=True, max_length=60, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'workflow',
                'db_table': 'core_workflow',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=256, null=True, unique=True)),
                ('abbr', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'permissions': (('inspect_deliveries', 'Can view released reports for obligations to client'),),
            },
        ),
        migrations.CreateModel(
            name='ClientGroupObjectPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Client')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClientUserObjectPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Client')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=512, storage=reportek.core.models.reporting.OverwriteFileSystemStorage(), upload_to=reportek.core.models.reporting.get_upload_path)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('restricted', models.BooleanField(default=False)),
                ('conversion_status', models.IntegerField(choices=[(-1, 'error'), (0, 'na'), (1, 'running'), (2, 'finished')], default=0)),
            ],
            options={
                'db_table': 'core_data_file',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Envelope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('coverage_note', models.CharField(blank=True, max_length=256, null=True)),
                ('coverage_start_year', models.IntegerField(blank=True, null=True)),
                ('coverage_end_year', models.IntegerField(blank=True, null=True)),
                ('coverage_interval', models.IntegerField(blank=True, choices=[(0, 'Whole year'), (1, 'First half'), (2, 'Second half'), (3, 'First quarter'), (4, 'Second quarter'), (5, 'Third quarter'), (6, 'Fourth quarter'), (7, 'January'), (8, 'February'), (9, 'March'), (10, 'April'), (11, 'May'), (12, 'June'), (13, 'July'), (14, 'August'), (15, 'September'), (16, 'October'), (17, 'November'), (18, 'December')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finalized', models.BooleanField(default=False)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=256, null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=500)),
                ('text', models.CharField(blank=True, max_length=200, null=True)),
                ('envelope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='core.Envelope')),
            ],
            options={
                'db_table': 'core_link',
            },
        ),
        migrations.CreateModel(
            name='Obligation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('terminated', models.BooleanField(default=False)),
                ('active_since', models.DateTimeField()),
                ('active_until', models.DateTimeField(null=True)),
                ('reporting_duration', models.SmallIntegerField(null=True)),
                ('reporting_frequency', models.SmallIntegerField(null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obligations', to='core.Client')),
                ('instrument', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obligations', to='core.Instrument')),
            ],
            options={
                'permissions': (('report_on_obligation', 'Can report on obligation'),),
            },
        ),
        migrations.CreateModel(
            name='ObligationGroupObjectPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Obligation')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ObligationSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('is_current', models.BooleanField(default=False)),
                ('draft', models.BooleanField(default=True)),
                ('schema', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=1024), size=None)),
                ('workflow_class', models.CharField(blank=True, choices=[('reportek.core.models.workflows.demo_auto_qa.DemoAutoQAWorkflow', 'DemoAutoQAWorkflow'), ('reportek.core.models.workflows.demo_auto_qa.DemoFailQAWorkflow', 'DemoFailQAWorkflow'), ('reportek.core.models.workflows.demo_auto_qa.DemoPassQAWorkflow', 'DemoPassQAWorkflow')], max_length=256, null=True)),
                ('qa_xmlrpc_uri', models.CharField(default='http://xmlconv.edw.ro:8080/RpcRouter', max_length=200)),
                ('obligation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='core.Obligation')),
            ],
            options={
                'verbose_name': 'Obligation Specification',
                'db_table': 'core_oblig_spec',
            },
        ),
        migrations.CreateModel(
            name='ObligationSpecReporter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'core_oblig_spec_reporter',
            },
        ),
        migrations.CreateModel(
            name='ObligationUserObjectPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Obligation')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QAJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qa_job_id', models.IntegerField()),
                ('qa_script_id', models.CharField(blank=True, max_length=20, null=True)),
                ('qa_script_name', models.CharField(blank=True, max_length=200, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('refreshing', models.BooleanField(default=False)),
                ('envelope_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_jobs', to='core.DataFile')),
            ],
            options={
                'db_table': 'core_qa_job',
            },
        ),
        migrations.CreateModel(
            name='QAJobResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.IntegerField(choices=[(0, 'READY'), (1, 'NOT_READY'), (2, 'FATAL_ERROR'), (3, 'LIGHT_ERROR')])),
                ('value', models.TextField(blank=True, null=True)),
                ('metatype', models.CharField(blank=True, max_length=60, null=True)),
                ('script_title', models.CharField(max_length=100)),
                ('feedback_status', models.CharField(choices=[('BLOCKER', 'BLOCKER'), ('ERROR', 'ERROR'), ('WARNING', 'WARNING'), ('INFO', 'INFO'), ('UNKNOWN', 'UNKNOWN')], max_length=40)),
                ('feedback_message', models.CharField(blank=True, max_length=200, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.QAJob')),
            ],
            options={
                'db_table': 'core_qa_job_result',
                'get_latest_by': 'updated_at',
            },
        ),
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=256, null=True, unique=True)),
                ('abbr', models.CharField(max_length=32, null=True, unique=True)),
                ('obligation_specs', models.ManyToManyField(through='core.ObligationSpecReporter', to='core.ObligationSpec')),
            ],
            options={
                'permissions': (('report_for_reporter', 'Can create and deliver envelopes for reporter'), ('collaborate_for_reporter', 'Can collaborate on envelopes for reporter'), ('audit_reporter', "Can audit reporter's envelopes")),
            },
        ),
        migrations.CreateModel(
            name='ReporterGroupObjectPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Reporter')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReporterSubdivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=128, null=True)),
            ],
            options={
                'verbose_name': 'Reporter Subdivision',
                'db_table': 'core_reporter_subdiv',
            },
        ),
        migrations.CreateModel(
            name='ReporterSubdivisionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=128, null=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdivision_categories', to='core.Reporter')),
            ],
            options={
                'verbose_name': 'Reporter Subdivision Category',
                'verbose_name_plural': 'Reporter Subdivision Categories',
                'db_table': 'core_reporter_subdiv_cat',
            },
        ),
        migrations.CreateModel(
            name='ReporterUserObjectPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Reporter')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReportingCycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('reporting_start_date', models.DateField()),
                ('reporting_end_date', models.DateField(blank=True, null=True)),
                ('is_open', models.BooleanField(default=True)),
                ('obligation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Obligation')),
                ('obligation_spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporting_cycles', to='core.ObligationSpec')),
            ],
            options={
                'db_table': 'core_reporting_cycle',
            },
        ),
        migrations.CreateModel(
            name='SupportFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=512, storage=reportek.core.models.reporting.OverwriteFileSystemStorage(), upload_to=reportek.core.models.reporting.get_upload_path)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('restricted', models.BooleanField(default=False)),
                ('envelope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supportfiles', to='core.Envelope')),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_support_file',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransitionEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField()),
                ('transition', models.CharField(max_length=60)),
                ('from_state', models.CharField(max_length=60)),
                ('to_state', models.CharField(max_length=60)),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'workflow event',
                'db_table': 'core_transition_event',
            },
        ),
        migrations.CreateModel(
            name='UploadToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, default=reportek.core.models.reporting.default_token, max_length=100, unique=True)),
                ('filename', models.CharField(max_length=256)),
                ('tus_id', models.CharField(blank=True, max_length=32, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(default=reportek.core.models.reporting.token_valid_until)),
                ('envelope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_tokens', to='core.Envelope')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_upload_token',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='reportersubdivision',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdivisions', to='core.ReporterSubdivisionCategory'),
        ),
        migrations.AddField(
            model_name='obligationspecreporter',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Reporter'),
        ),
        migrations.AddField(
            model_name='obligationspecreporter',
            name='spec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ObligationSpec'),
        ),
        migrations.AddField(
            model_name='obligationspecreporter',
            name='subdivision_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ReporterSubdivisionCategory'),
        ),
        migrations.AddField(
            model_name='obligationspec',
            name='reporters',
            field=models.ManyToManyField(through='core.ObligationSpecReporter', to='core.Reporter'),
        ),
        migrations.AddField(
            model_name='envelope',
            name='obligation_spec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envelopes', to='core.ObligationSpec'),
        ),
        migrations.AddField(
            model_name='envelope',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envelopes', to='core.Reporter'),
        ),
        migrations.AddField(
            model_name='envelope',
            name='reporter_subdivision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='envelopes', to='core.ReporterSubdivision'),
        ),
        migrations.AddField(
            model_name='envelope',
            name='reporting_cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envelopes', to='core.ReportingCycle'),
        ),
        migrations.AddField(
            model_name='envelope',
            name='workflow',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='envelope', to='core.BaseWorkflow'),
        ),
        migrations.AddField(
            model_name='datafile',
            name='envelope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datafiles', to='core.Envelope'),
        ),
        migrations.AddField(
            model_name='datafile',
            name='original_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='converted_files', to='core.DataFile'),
        ),
        migrations.AddField(
            model_name='datafile',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DemoAutoQAWorkflow',
            fields=[
            ],
            options={
                'verbose_name': 'Workflow - Auto QA',
                'verbose_name_plural': 'Workflows - Auto QA ',
                'proxy': True,
                'indexes': [],
            },
            bases=('core.baseworkflow',),
        ),
        migrations.AlterUniqueTogether(
            name='transitionevent',
            unique_together={('timestamp', 'object_id', 'from_state', 'to_state')},
        ),
        migrations.AlterUniqueTogether(
            name='supportfile',
            unique_together={('envelope', 'file')},
        ),
        migrations.AlterUniqueTogether(
            name='reporteruserobjectpermission',
            unique_together={('user', 'permission', 'content_object')},
        ),
        migrations.AlterUniqueTogether(
            name='reportersubdivisioncategory',
            unique_together={('reporter', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='reportersubdivision',
            unique_together={('category', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='reportergroupobjectpermission',
            unique_together={('group', 'permission', 'content_object')},
        ),
        migrations.AlterUniqueTogether(
            name='qajob',
            unique_together={('envelope_file', 'qa_job_id')},
        ),
        migrations.AlterUniqueTogether(
            name='obligationuserobjectpermission',
            unique_together={('user', 'permission', 'content_object')},
        ),
        migrations.AlterUniqueTogether(
            name='obligationspec',
            unique_together={('obligation', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='obligationgroupobjectpermission',
            unique_together={('group', 'permission', 'content_object')},
        ),
        migrations.AlterUniqueTogether(
            name='link',
            unique_together={('envelope', 'link')},
        ),
        migrations.AlterUniqueTogether(
            name='datafile',
            unique_together={('envelope', 'file')},
        ),
        migrations.AlterUniqueTogether(
            name='clientuserobjectpermission',
            unique_together={('user', 'permission', 'content_object')},
        ),
        migrations.AlterUniqueTogether(
            name='clientgroupobjectpermission',
            unique_together={('group', 'permission', 'content_object')},
        ),
        migrations.CreateModel(
            name='DemoFailQAWorkflow',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('core.demoautoqaworkflow',),
        ),
        migrations.CreateModel(
            name='DemoPassQAWorkflow',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('core.demoautoqaworkflow',),
        ),
    ]
