# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-02 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obligationspec',
            name='is_current',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='reportingcycle',
            name='is_open',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
