# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-27 14:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportekuser',
            options={'permissions': (('act_as_reportnet_api', 'This is the user of another Reportnet service'),)},
        ),
    ]
