# Generated by Django 2.0.4 on 2018-04-23 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('restricted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('envelope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_comments', to='core.Envelope')),
            ],
            options={
                'db_table': 'core_feedback_comm',
            },
        ),
        migrations.DeleteModel(
            name='DemoAutoQAWorkflow',
        ),
        migrations.DeleteModel(
            name='DemoFailQAWorkflow',
        ),
        migrations.DeleteModel(
            name='DemoPassQAWorkflow',
        ),
        migrations.CreateModel(
            name='ReferenceWorkflow',
            fields=[
            ],
            options={
                'verbose_name': 'Workflow - Reference',
                'verbose_name_plural': 'Workflows - Reference',
                'proxy': True,
                'indexes': [],
            },
            bases=('core.baseworkflow',),
        ),
        migrations.AlterField(
            model_name='baseworkflow',
            name='type',
            field=models.CharField(choices=[('core.referenceworkflow', 'Workflow - Reference')], db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='obligationspec',
            name='workflow_class',
            field=models.CharField(blank=True, choices=[('reportek.core.models.workflows.reference.ReferenceWorkflow', 'ReferenceWorkflow')], max_length=256, null=True),
        ),
    ]
