# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import edw.djutils.protected.fields
import reportek.core.models.reporting


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envelopefile',
            name='envelope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.Envelope'),
        ),
        migrations.AlterField(
            model_name='envelopefile',
            name='file',
            field=edw.djutils.protected.fields.ProtectedFileField(upload_to=reportek.core.models.reporting.EnvelopeFile.get_envelope_directory),
        ),
    ]
