# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-06 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180202_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obligationspecreporter',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_mapping', to='core.Reporter'),
        ),
        migrations.AlterField(
            model_name='obligationspecreporter',
            name='spec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporter_mapping', to='core.ObligationSpec'),
        ),
        migrations.AlterField(
            model_name='reportingcycle',
            name='reporting_end_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportingcycle',
            name='reporting_start_date',
            field=models.DateField(db_index=True),
        ),
    ]
