# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-15 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180111_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envelope',
            name='obligation',
        ),
        migrations.AddField(
            model_name='envelope',
            name='reporter_subdivision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='envelopes', to='core.ReporterSubdivision'),
        ),
        migrations.AlterField(
            model_name='envelope',
            name='obligation_spec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envelopes', to='core.ObligationSpec'),
        ),
        migrations.AlterField(
            model_name='envelope',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envelopes', to='core.Reporter'),
        ),
        migrations.AlterField(
            model_name='envelope',
            name='reporting_cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envelopes', to='core.ReportingCycle'),
        ),
        migrations.AlterField(
            model_name='envelope',
            name='workflow',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='envelopes', to='core.BaseWorkflow'),
        ),
        migrations.AlterField(
            model_name='obligation',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obligations', to='core.Client'),
        ),
        migrations.AlterField(
            model_name='obligation',
            name='instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obligations', to='core.Instrument'),
        ),
        migrations.AlterField(
            model_name='obligationspec',
            name='workflow_class',
            field=models.CharField(blank=True, choices=[('reportek.core.models.workflows.demo_auto_qa.DemoAutoQAWorkflow', 'DemoAutoQAWorkflow'), ('reportek.core.models.workflows.demo_auto_qa.DemoFailQAWorkflow', 'DemoFailQAWorkflow'), ('reportek.core.models.workflows.demo_auto_qa.DemoPassQAWorkflow', 'DemoPassQAWorkflow')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='reportersubdivision',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdivisions', to='core.ReporterSubdivisionCategory'),
        ),
        migrations.AlterField(
            model_name='reportersubdivisioncategory',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdivision_categories', to='core.Reporter'),
        ),
        migrations.AlterField(
            model_name='reportingcycle',
            name='obligation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporting_cycles', to='core.Obligation'),
        ),
        migrations.AlterField(
            model_name='reportingcycle',
            name='obligation_spec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporting_cycles', to='core.ObligationSpec'),
        ),
    ]
