# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-27 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import edw.djutils.protected.fields
import reportek.core.models.reporting


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180227_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvelopeOriginalFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', edw.djutils.protected.fields.ProtectedFileField(max_length=512, upload_to=reportek.core.models.reporting.EnvelopeOriginalFile.get_envelope_directory)),
                ('name', models.CharField(max_length=256, validators=[reportek.core.models.reporting.validate_filename])),
                ('envelope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_files', to='core.Envelope')),
            ],
            options={
                'db_table': 'original_envelope_file',
            },
        ),
        migrations.AlterModelOptions(
            name='reportekuser',
            options={'permissions': (('act_as_reportnet_api', 'This is the user of another Reportnet service'),), 'verbose_name': 'user'},
        ),
        migrations.AlterField(
            model_name='obligationspec',
            name='workflow_class',
            field=models.CharField(blank=True, choices=[('reportek.core.models.workflows.demo_auto_qa.DemoAutoQAWorkflow', 'DemoAutoQAWorkflow'), ('reportek.core.models.workflows.demo_auto_qa.DemoPassQAWorkflow', 'DemoPassQAWorkflow'), ('reportek.core.models.workflows.demo_auto_qa.DemoFailQAWorkflow', 'DemoFailQAWorkflow')], max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='envelopefile',
            name='original_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='envelope_files', to='core.EnvelopeOriginalFile'),
        ),
    ]
