# Generated by Django 2.0.4 on 2018-04-23 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180423_1128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transitionevent',
            options={'ordering': ['-timestamp'], 'verbose_name': 'workflow event'},
        ),
    ]
