# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-03 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171103_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='acronym',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
