# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-05 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180227_1448'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportekuser',
            options={'permissions': (('act_as_reportnet_api', 'This is the user of another Reportnet service'),), 'verbose_name': 'user'},
        ),
        migrations.AlterUniqueTogether(
            name='envelope',
            unique_together=set([]),
        ),
    ]
