# Generated by Django 2.0.4 on 2018-04-26 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180423_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvelopeObligationSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='envelope',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='envelope',
            old_name='updated_at',
            new_name='updated',
        ),
        migrations.RemoveField(
            model_name='envelope',
            name='obligation_spec',
        ),
        migrations.AddField(
            model_name='envelopeobligationspec',
            name='envelope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Envelope'),
        ),
        migrations.AddField(
            model_name='envelopeobligationspec',
            name='obligation_spec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ObligationSpec'),
        ),
        migrations.AddField(
            model_name='envelopeobligationspec',
            name='reporting_cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ReportingCycle'),
        ),
        migrations.AddField(
            model_name='envelope',
            name='obligation_specs',
            field=models.ManyToManyField(through='core.EnvelopeObligationSpec', to='core.ObligationSpec'),
        ),
        migrations.AlterUniqueTogether(
            name='envelopeobligationspec',
            unique_together={('envelope', 'obligation_spec')},
        ),
    ]
