# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-09 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180206_1214'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='envelope',
            unique_together=set([]),
        ),
    ]
