# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 08:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import edw.djutils.protected.fields
import reportek.core.models.reporting


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180305_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvelopeOriginalFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', edw.djutils.protected.fields.ProtectedFileField(max_length=512, upload_to=reportek.core.models.reporting.EnvelopeOriginalFile.get_envelope_directory)),
                ('name', models.CharField(max_length=256, validators=[reportek.core.models.reporting.validate_filename])),
                ('envelope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_files', to='core.Envelope')),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'original_envelope_file',
            },
        ),
        migrations.AlterField(
            model_name='obligationspec',
            name='workflow_class',
            field=models.CharField(blank=True, choices=[('reportek.core.models.workflows.demo_auto_qa.DemoPassQAWorkflow', 'DemoPassQAWorkflow'), ('reportek.core.models.workflows.demo_auto_qa.DemoFailQAWorkflow', 'DemoFailQAWorkflow'), ('reportek.core.models.workflows.demo_auto_qa.DemoAutoQAWorkflow', 'DemoAutoQAWorkflow')], max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='envelopefile',
            name='original_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='envelope_files', to='core.EnvelopeOriginalFile'),
        ),
    ]
