# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180306_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='envelope',
            name='coverage_note',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='envelope',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
