# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 10:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_instrument'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obligation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('last_update', models.DateField()),
                ('next_deadline', models.DateField(blank=True, null=True)),
                ('next_deadline2', models.DateField(blank=True, null=True)),
                ('report_freq_months', models.IntegerField(blank=True, null=True)),
                ('report_freq', models.CharField(blank=True, max_length=30, null=True)),
                ('continuous_reporting', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Client')),
                ('delivery_countries', models.ManyToManyField(to='core.Country')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Instrument')),
            ],
        ),
    ]
