# Generated by Django 2.0.4 on 2018-04-26 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180426_0824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envelope',
            name='reporting_cycle',
        ),
    ]
