# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-07 12:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180306_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='envelopefile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='envelopefile',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='envelopeoriginalfile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='envelopeoriginalfile',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
