# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_obligation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obligation',
            name='instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Instrument'),
        ),
    ]
