# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import reportek.core.models.reporting


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20171114_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envelopefile',
            name='name',
            field=models.CharField(max_length=256, validators=[reportek.core.models.reporting.validate_filename]),
        ),
    ]
