# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 16:50
from __future__ import unicode_literals

import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20171106_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('countries', models.ManyToManyField(to='core.Country')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Envelope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=256)),
                ('reporting_period', django.contrib.postgres.fields.ranges.DateRangeField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Country')),
            ],
        ),
        migrations.CreateModel(
            name='ObligationGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='obligationgroup',
            name='workflow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Workflow'),
        ),
        migrations.AddField(
            model_name='envelope',
            name='obligation_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ObligationGroup'),
        ),
        migrations.AddField(
            model_name='collection',
            name='obligation_groups',
            field=models.ManyToManyField(to='core.ObligationGroup'),
        ),
        migrations.AlterUniqueTogether(
            name='envelope',
            unique_together=set([('obligation_group', 'country', 'reporting_period')]),
        ),
    ]
