# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-26 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180307_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='envelopeoriginalfile',
            name='restricted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='envelopefile',
            name='envelope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envelopefiles', to='core.Envelope'),
        ),
        migrations.AlterField(
            model_name='envelopeoriginalfile',
            name='envelope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envelopeoriginalfiles', to='core.Envelope'),
        ),
        migrations.AlterUniqueTogether(
            name='envelopeoriginalfile',
            unique_together=set([('envelope', 'name')]),
        ),
        migrations.AlterModelTable(
            name='envelopeoriginalfile',
            table='core_envelope_original_file',
        ),
    ]
