# Generated by Django 2.0.4 on 2018-05-02 15:23

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180427_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('coverage_start_year', models.IntegerField(blank=True, null=True)),
                ('coverage_end_year', models.IntegerField(blank=True, null=True)),
                ('coverage_interval', models.IntegerField(blank=True, choices=[(0, 'Whole year'), (1, 'First half'), (2, 'Second half'), (3, 'First quarter'), (4, 'Second quarter'), (5, 'Third quarter'), (6, 'Fourth quarter'), (7, 'January'), (8, 'February'), (9, 'March'), (10, 'April'), (11, 'May'), (12, 'June'), (13, 'July'), (14, 'August'), (15, 'September'), (16, 'October'), (17, 'November'), (18, 'December')], null=True)),
                ('coverage_note', models.CharField(blank=True, max_length=256, null=True)),
                ('allows_envelopes', models.BooleanField(default=True)),
                ('allows_collections', models.BooleanField(default=False)),
                ('allows_referrals', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('obligations', models.ManyToManyField(related_name='collections', to='core.Obligation')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.Collection')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Reporter')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
