# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20171115_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='envelope',
            name='finalized',
            field=models.BooleanField(default=False),
        ),
    ]
