# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_envelope_finalized'),
    ]

    operations = [
        migrations.AddField(
            model_name='obligation',
            name='first_reporting',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obligation',
            name='terminated',
            field=models.BooleanField(default=False),
        ),
    ]
