# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-02 14:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180327_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envelope',
            name='author',
        ),
        migrations.AddField(
            model_name='envelope',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
