# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_envelope_finalized'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obligationgroup',
            name='workflow',
        ),
        migrations.AddField(
            model_name='obligationgroup',
            name='workflow_class',
            field=models.CharField(blank=True, choices=[('DemoAutoQAWorkflow', 'reportek.core.models.workflows.demo_auto_qa.DemoAutoQAWorkflow')], max_length=256, null=True),
        ),
    ]
