# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 19:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20171107_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='WFInitialState',
            fields=[
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='initial_state', serialize=False, to='core.WorkFlow')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.WFState', unique=True)),
            ],
            options={
                'verbose_name': 'workflow initial state',
                'verbose_name_plural': 'workflow initial states',
            },
        ),
        migrations.AlterModelOptions(
            name='reportone',
            options={'verbose_name': 'report'},
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='initial_state',
        ),
        migrations.AlterField(
            model_name='basereport',
            name='type',
            field=models.CharField(choices=[('core.reportone', 'report')], db_index=True, max_length=255),
        ),
    ]
