# Generated by Django 2.0.4 on 2018-05-02 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='deprecated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='collection',
            name='obligations',
            field=models.ManyToManyField(blank=True, related_name='collections', to='core.Obligation'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Reporter'),
        ),
    ]
