# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20171107_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
