# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 08:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20171120_1231'),
        ('core', '0008_auto_20171120_1449'),
    ]

    operations = [
    ]
