# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-03 14:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import edw.djutils.protected.fields
import reportek.core.models.reporting


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180402_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvelopeLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=500)),
                ('text', models.CharField(blank=True, max_length=200, null=True)),
                ('envelope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='core.Envelope')),
            ],
            options={
                'db_table': 'core_envelope_link',
            },
        ),
        migrations.CreateModel(
            name='EnvelopeSupportFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', edw.djutils.protected.fields.ProtectedFileField(max_length=512, upload_to=reportek.core.models.reporting.BaseEnvelopeFile.get_envelope_directory)),
                ('name', models.CharField(max_length=256, validators=[reportek.core.models.reporting.validate_filename])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('restricted', models.BooleanField(default=False)),
                ('envelope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_files', to='core.Envelope')),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_envelope_support_file',
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='envelopesupportfile',
            unique_together=set([('envelope', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='envelopelink',
            unique_together=set([('envelope', 'link')]),
        ),
    ]
