# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 09:37
from __future__ import unicode_literals

import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_merge_20171121_0852'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportingPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', django.contrib.postgres.fields.ranges.DateRangeField()),
                ('open', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='reportingperiod',
            name='obligation_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ObligationGroup'),
        ),
        migrations.AlterUniqueTogether(
            name='reportingperiod',
            unique_together=set([('obligation_group', 'period')]),
        ),
        migrations.AlterUniqueTogether(
            name='envelope',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='envelope',
            name='reporting_period',
        ),
        migrations.AddField(
            model_name='envelope',
            name='reporting_period',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.ReportingPeriod'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='envelope',
            unique_together=set([('obligation_group', 'country', 'reporting_period')]),
        ),
    ]
