# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20171107_2018'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wftransition',
            unique_together=set([('name', 'workflow')]),
        ),
    ]
