# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 08:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20171107_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='basereport',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Country'),
            preserve_default=False,
        ),
    ]
