# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 09:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import reportek.core.models.reporting


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_auto_20171122_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, default=reportek.core.models.reporting.default_token, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('envelope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_tokens', to='core.Envelope')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='DemoFailQAWorkflow',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('core.demoautoqaworkflow',),
        ),
        migrations.CreateModel(
            name='DemoPassQAWorkflow',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('core.demoautoqaworkflow',),
        ),
        migrations.AlterField(
            model_name='baseworkflow',
            name='type',
            field=models.CharField(choices=[('core.demoautoqaworkflow', 'Workflow - Auto QA'), ('core.demofailqaworkflow', 'demo fail qa workflow'), ('core.demopassqaworkflow', 'demo pass qa workflow')], db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='obligationgroup',
            name='workflow_class',
            field=models.CharField(blank=True, choices=[('reportek.core.models.workflows.demo_auto_qa.DemoPassQAWorkflow', 'DemoPassQAWorkflow'), ('reportek.core.models.workflows.demo_auto_qa.DemoAutoQAWorkflow', 'DemoAutoQAWorkflow'), ('reportek.core.models.workflows.demo_auto_qa.DemoFailQAWorkflow', 'DemoFailQAWorkflow')], max_length=256, null=True),
        ),
    ]
