# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import reportek.core.models.reporting


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20171205_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadtoken',
            name='valid_until',
            field=models.DateTimeField(default=reportek.core.models.reporting.token_valid_until),
        ),
        migrations.AlterField(
            model_name='uploadtoken',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
