# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 12:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_basereport_country'),
        ('core', '0007_auto_20171107_1650'),
    ]

    operations = [
    ]
