# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20171205_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadtoken',
            name='filename',
            field=models.CharField(max_length=256, blank=True, null=True),
            preserve_default=False,
        ),
    ]
