# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 08:59
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0014_auto_20171109_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseWorkflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('core.demoautoqaworkflow', 'Workflow - Auto QA')], db_index=True, max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=60)),
                ('envelope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Envelope')),
            ],
            options={
                'verbose_name': 'workflow',
            },
        ),
        migrations.CreateModel(
            name='TransitionEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField()),
                ('transition', models.CharField(max_length=60)),
                ('from_state', models.CharField(max_length=60)),
                ('to_state', models.CharField(max_length=60)),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'workflow event',
            },
        ),
        migrations.RemoveField(
            model_name='wfinitialstate',
            name='state',
        ),
        migrations.RemoveField(
            model_name='wfinitialstate',
            name='workflow',
        ),
        migrations.AlterUniqueTogether(
            name='wfstate',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='wfstate',
            name='workflow',
        ),
        migrations.AlterUniqueTogether(
            name='wftransition',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='wftransition',
            name='target',
        ),
        migrations.RemoveField(
            model_name='wftransition',
            name='workflow',
        ),
        migrations.AlterUniqueTogether(
            name='wftransitionsource',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='wftransitionsource',
            name='state',
        ),
        migrations.RemoveField(
            model_name='wftransitionsource',
            name='transition',
        ),
        migrations.RemoveField(
            model_name='basereport',
            name='wf_state',
        ),
        migrations.RemoveField(
            model_name='basereport',
            name='workflow',
        ),
        migrations.RemoveField(
            model_name='reportlog',
            name='from_state',
        ),
        migrations.RemoveField(
            model_name='reportlog',
            name='to_state',
        ),
        migrations.RemoveField(
            model_name='reportlog',
            name='transition',
        ),
        migrations.DeleteModel(
            name='WFInitialState',
        ),
        migrations.DeleteModel(
            name='WFState',
        ),
        migrations.DeleteModel(
            name='WFTransition',
        ),
        migrations.DeleteModel(
            name='WFTransitionSource',
        ),
        migrations.DeleteModel(
            name='WorkFlow',
        ),
        migrations.CreateModel(
            name='DemoAutoQAWorkflow',
            fields=[
            ],
            options={
                'verbose_name': 'Workflow - Auto QA',
                'verbose_name_plural': 'Workflows - Auto QA ',
                'proxy': True,
                'indexes': [],
            },
            bases=('core.baseworkflow',),
        ),
        migrations.AlterUniqueTogether(
            name='transitionevent',
            unique_together=set([('timestamp', 'object_id', 'from_state', 'to_state')]),
        ),
    ]
