# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import reportek.core.models.reporting


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20171109_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvelopeFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=reportek.core.models.reporting.EnvelopeFile.get_envelope_directory)),
                ('envelope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Envelope')),
            ],
        ),
    ]
