# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20171206_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadtoken',
            name='tus_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
