# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-14 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20171207_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='QAJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qa_job_id', models.IntegerField()),
                ('completed', models.BooleanField(default=False)),
                ('refreshing', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='QAJobResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.IntegerField(choices=[(0, 'READY'), (1, 'NOT_READY'), (2, 'FATAL_ERROR'), (3, 'LIGHT_ERROR')])),
                ('value', models.TextField(blank=True, null=True)),
                ('metatype', models.CharField(blank=True, max_length=60, null=True)),
                ('script_title', models.CharField(max_length=100)),
                ('feedback_status', models.CharField(choices=[('BLOCKER', 'BLOCKER'), ('ERROR', 'ERROR'), ('WARNING', 'WARNING'), ('INFO', 'INFO'), ('UNKNOWN', 'UNKNOWN')], max_length=40)),
                ('feedback_message', models.CharField(blank=True, max_length=200, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.QAJob')),
            ],
            options={
                'get_latest_by': 'updated_at',
            },
        ),
        migrations.AddField(
            model_name='envelopefile',
            name='xml_schema',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='obligationgroup',
            name='qa_xmlrpc_uri',
            field=models.CharField(default='http://localhost:1082/RpcRouter', max_length=200),
        ),
        migrations.AlterField(
            model_name='uploadtoken',
            name='filename',
            field=models.CharField(default='file.xml', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qajob',
            name='envelope_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_jobs', to='core.EnvelopeFile'),
        ),
        migrations.AlterUniqueTogether(
            name='qajob',
            unique_together=set([('envelope_file', 'qa_job_id')]),
        ),
    ]
