# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20171110_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseworkflow',
            name='previous_state',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
