# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 09:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20171110_1546'),
        ('core', '0015_envelopefile'),
    ]

    operations = [
    ]
