# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 09:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_merge_20171113_0900'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='baseworkflow',
            table='core_workflow',
        ),
    ]
