# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20171113_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseworkflow',
            name='current_state',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='baseworkflow',
            name='previous_state',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
