# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20171113_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseworkflow',
            name='envelope',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workflow', to='core.Envelope'),
        ),
    ]
