# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20171113_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseworkflow',
            name='envelope',
        ),
        migrations.AddField(
            model_name='envelope',
            name='workflow',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='envelope', to='core.BaseWorkflow'),
        ),
        migrations.AddField(
            model_name='obligation',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ObligationGroup'),
        ),
        migrations.AlterField(
            model_name='obligationgroup',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.BaseWorkflow'),
        ),
    ]
