"""
Django settings for reportek_site project.

Generated by 'django-admin startproject' using Django 1.11.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# repo root dir
ROOT_DIR = os.path.dirname(BASE_DIR)
PARENT_DIR = os.path.dirname(ROOT_DIR)

if os.getenv('DOCKER_CONTAINER'):
    POSTGRES_HOST = 'postgres'
else:
    POSTGRES_HOST = '127.0.0.1'

POSTGRES_PASSWORD = '' if os.getenv('TRAVIS') else 'postgres'

REPORTEK_DOMAIN = os.getenv('REPORTEK_DOMAIN')
REPORTEK_USE_TLS = True

TUSD_UPLOADS_DIR = '/var/tusd/data'
ALLOWED_UPLOADS_ARCHIVE_EXTENSIONS = ['zip']
ALLOWED_UPLOADS_EXTENSIONS = ['xml']


# Celery
CELERY_BROKER_HOST = 'localhost'
CELERY_BROKER_VHOST = 'reportek'
CELERY_BROKER_USER = 'reportek'
CELERY_BROKER_PWD = 'reportek'
CELERY_BROKER_URL = f'amqp://{CELERY_BROKER_USER}:{CELERY_BROKER_PWD}@{CELERY_BROKER_HOST}//{CELERY_BROKER_VHOST}'
CELERY_RESULT_BACKEND = 'rpc'


# QA
QA_DEFAULT_XMLRPC_URI = os.getenv('QA_DEFAULT_XMLRPC_URI')
QA_FETCH_RESULTS_FREQUENCY = os.getenv('QA_FETCH_RESULTS_FREQUENCY', 60)  # seconds


# Toggles preservation of archive paths in names of unpacked files,
# i.e. 'dir1/dir2/file.xml' becomes 'dir1_dir2_file.xml'.
# This provides overwrite protection for cases where the archive
# contains files with the same name in several directories.
ARCHIVE_PATH_PREFIX = True


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '$l7kk5pin%!m7hr5lzy-pagdo*1o8$wx2&rxxes@e%mo3(ap$&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'false').lower() == 'true'

ALLOWED_HOSTS = [os.getenv('ALLOWED_HOSTS')]


# Application definition

INSTALLED_APPS = [
    'reportek.core.apps.Config',
    'django_xworkflows',
    'typedmodels',
    'rest_framework',
    'rest_framework.authtoken',
    'django_jinja',
    'django_extensions',
    'django_object_actions',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'reportek.site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django_jinja.backend.Jinja2',
        'DIRS': [
            os.path.join(ROOT_DIR, 'templates'),
        ],
        'APP_DIRS': False,
        'OPTIONS': {
            # everything under our template dir is a jinja template
            "match_extension": None,
            # TODO: enable bytecode cache in production
        },
    },
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'reportek.site.wsgi.application'


# DRF

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ),
    'TEST_REQUEST_DEFAULT_FORMAT': 'json',
}


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'postgres',
        'HOST': POSTGRES_HOST,
        'USER': 'postgres',
        'PASSWORD': POSTGRES_PASSWORD
    }
}


SILENCED_SYSTEM_CHECKS = [
    'fields.W342',  # Disable OneToOneField recommendation
]


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_URL = '/static/'

MEDIA_ROOT = os.path.join(PARENT_DIR, 'uploads')
MEDIA_URL = '/files/'

PROTECTED_ROOT = os.path.join(PARENT_DIR, 'protected_uploads')
PROTECTED_URL = '/protected-files/'


FIXTURE_DIRS = [
    os.path.join(ROOT_DIR, 'data', 'fixtures')
]


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {
            'format': '%(asctime)s [%(levelname)s] %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
        },
        'reportek.workflows': {
            'handlers': ['console'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
        },
        'reportek.qa': {
            'handlers': ['console'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
        },
        'reportek.tasks': {
            'handlers': ['console'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
        },
    },
}


try:
    from .localsettings import *
except ImportError:
    pass
